### ISSUE TITLE
elapsed time in BUILD_STATUS_DB.txt?

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/BBS#112]
It seems worthwhile to record the elapsed time for each phase when possible
in a centralized place.  Otherwise one has to hunt through the individual
package artifacts.  BUILD_STATUS_DB.txt seems a natural place for the time?

**Comment by hpages** [comment]
What about implementing this in `BiocPkgTools::biocBuildReport()`? This function already downloads `report.tgz` and aggregates all the information contained in the small individual `<pkg>/raw-results/info.dcf` files to the tibble returned by the function.

Maybe the same could be done with the `<pkg>/raw-results/<node>/*-summary.dcf` files? Since the function is already paying the cost of downloading and extracting `report.tgz`, the only additional cost would be to import the `StartedAt`, `EndedAt`, `EllapsedTime` fields from the thousands of `*-summary.dcf` files. This can be done with something like:
```
summary_files <- list.files(".", pattern="-summary\\.dcf$", full.names=TRUE, recursive=TRUE)
length(summary_files)
# [1] 22285

fields <- c("Package", "StartedAt", "EndedAt", "EllapsedTime")
summaries <- lapply(summary_files, function(f) read.dcf(f)[ , fields])
m2 <- matrix(unlist(summaries), ncol=length(fields), byrow=TRUE, dimnames=list(NULL, fields))

m1 <- matrix(unlist(strsplit(summary_files, split="/", fixed=TRUE)), ncol=5, byrow=TRUE)
m1 <- m1[, c(2, 4, 5)]
colnames(m1) <- c("pkg", "node", "stage")
m1[ , "stage"] <- sub("-summary.dcf$", "", m1[ , "stage"])

m <- cbind(m1, m2[ , -1])

dim(m)
# [1] 22285     6

head(m)
#      pkg  node        stage      StartedAt                                     
# [1,] "a4" "merida1"   "buildbin" "2021-12-20 07:18:47 -0500 (Mon, 20 Dec 2021)"
# [2,] "a4" "merida1"   "buildsrc" "2021-12-19 16:27:35 -0500 (Sun, 19 Dec 2021)"
# [3,] "a4" "merida1"   "checksrc" "2021-12-19 21:51:28 -0500 (Sun, 19 Dec 2021)"
# [4,] "a4" "merida1"   "install"  "2021-12-19 15:38:17 -0500 (Sun, 19 Dec 2021)"
# [5,] "a4" "nebbiolo1" "buildsrc" "2021-12-19 15:42:59 -0500 (Sun, 19 Dec 2021)"
# [6,] "a4" "nebbiolo1" "checksrc" "2021-12-19 18:06:41 -0500 (Sun, 19 Dec 2021)"
#      EndedAt                                        EllapsedTime   
# [1,] "2021-12-20 07:19:24 -0500 (Mon, 20 Dec 2021)" "37.5 seconds" 
# [2,] "2021-12-19 16:30:50 -0500 (Sun, 19 Dec 2021)" "194.4 seconds"
# [3,] "2021-12-19 21:53:25 -0500 (Sun, 19 Dec 2021)" "117.1 seconds"
# [4,] "2021-12-19 15:38:53 -0500 (Sun, 19 Dec 2021)" "35.8 seconds" 
# [5,] "2021-12-19 15:44:44 -0500 (Sun, 19 Dec 2021)" "104.8 seconds"
# [6,] "2021-12-19 18:07:45 -0500 (Sun, 19 Dec 2021)" "64.2 seconds" 
```
Takes about 3.4 sec. on my laptop so maybe not so bad?

@LiNk-NY Any chance something like this could be added to `BiocPkgTools::biocBuildReport()`?

H.

**Comment by vjcitn** [comment]
Very nice.  Great demonstration of efficiency of list.files.  I had been running a loop.  I think the statistics are useful, and if a uniform unit (seconds) can be employed then making the time column numeric would be appropriate.  Not a super high priority at the moment but those numbers will be used when available in the package.

**Comment by hpages** [comment]
Maybe open an issue under **BiocPkgTools** for that? https://github.com/seandavi/BiocPkgTools/issues

Thanks
