### ISSUE TITLE
Document installation on Mac for GLPK for Bioc pkg MMUPHin

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#206]

**Comment by hpages** [comment]
The **MMUPHin** authors need to put this in their `SystemRequirements`.

The **igraph** package has:
```
SystemRequirements: gmp (optional), libxml2 (optional), glpk (>= 4.57, optional), C++11
```

But it looks like glpk is a hard requirement for **MMUPHin** (their vignette relies on it) so they need to put `glpk (>= 4.57)`.

**Comment by jwokaty** [comment]
I see that it's still failing on lconway and kjohnson. It's reporting that it can't find glpk. The paths are the same as on merida1 when it wasn't listed as a requirement, though I found a discussion that it likely was.

**Comment by hpages** [comment]
I don't see `glpk-5.0-darwin.17-x86_64.tar.xz` in `~biocbuild/Downloads/` on lconway. How did you install glpk on these machines?

**Comment by jwokaty** [comment]
I used the Quick Install instructions on https://mac.r-project.org/bin/

**Comment by hpages** [comment]
Hmm... I wonder whether **igraph** needs to be reinstalled of what. I'm going to try a few things.

**Comment by jwokaty** [comment]
I didn't think of reinstalling `igraph`, so that could be it.

**Comment by hpages** [comment]
Yeah, reinstalling **igraph** solves the problem. It's really weird though because I reinstalled the binary, and Mac binaries are usually _statically_ linked so they actually don't need any system libraries to be present on the user machine. **igraph** must be handling this in an unusual way.

We need to document the reinstall step.

I only did this on lconway. Hopefully that'll work on kjohnson too.

**Comment by jwokaty** [comment]
Thank you!
