### ISSUE TITLE
mark BrowserViz and BrowserVizDemo unsupported in windows

### ISSUE THREAD

**Issue by vobencha** [Bioconductor/BBS#29]
httpuv package does not yet support a daemonized server on windows

**Comment by vobencha** [comment]
Done in release and devel.

**Comment by b-long** [comment]
For anyone coming here in the future, the diff that solves this issue is here : 
\- https://github.com/Bioconductor-mirror/BrowserViz/commit/0f397592002f3750d549f7d8bc50e6d795703c58
\- https://github.com/Bioconductor-mirror/BrowserVizDemo/commit/753a57600b3b478e2d6ff2f6dde46483e4da1c26

cc/ @jimhester
