### ISSUE TITLE
meat file created

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#311]
Somehow a `meat` file gets created, which produces the error below. I've created the meat file on merida1 where I noticed it was having problems. Generally, we shouldn't have to create the meat directory; it should be created during the run if it doesn't exist.

```

BBS> ==============================================================
BBS> [STAGE3] STARTING STAGE3 at Sat Jun 17 08:00:00 2023
BBS>   (Re)make BBS_CENTRAL_BASEURL/products-in/merida1/buildsrc/... OK
BBS>   Updating BBS_WORK_TOPDIR/NodeInfo
BBS>   runJob(): /Library/Frameworks/R.framework/Resources/bin/Rscript -e "sessionInfo()"
BBS>     pid = 17796 / time [] = 0.64 seconds / retcode = 0 / OK
BBS>   runJob(): /Library/Frameworks/R.framework/Resources/bin/Rscript -e "options(width=500);print(installed.packages()[,c('LibPath','Version','Built')],quote=FALSE)"
BBS>     pid = 17817 / time [] = 6.01 seconds / retcode = 0 / OK
BBS>   cd BBS_WORK_TOPDIR
BBS>   Sending NodeInfo to BBS_CENTRAL_BASEURL/products-in/merida1/:
BBS>   runJob(): /usr/bin/rsync --rsh 'ssh -F /Users/biocbuild/.ssh/config' -rl --delete --delete-excluded --exclude='.svn' --exclude='.git' --exclude='.github' --exclude='.git_*' NodeInfo biocbuild@nebbiolo1:/home/biocbuild/public_html/BBS/3.17/bioc-longtests/products-in/merida1
BBS>     pid = 18058 / time [] = 1.68 seconds / retcode = 0 / OK
BBS> [STAGE3] cd BBS_MEAT_PATH
BBS> [get_list_of_target_pkgs] downloading meat-index.dcf ... ok
Traceback (most recent call last):
  File "/Users/biocbuild/BBS/BBS-run.py", line 817, in <module>
    STAGE3()
  File "/Users/biocbuild/BBS/BBS-run.py", line 612, in STAGE3
    os.chdir(meat_path)
NotADirectoryError: [Errno 20] Not a directory: '/Users/biocbuild/bbs-3.17-bioc-longtests/meat'
```

(I added merida1 to the long tests around 6/10 but it hasn't built successfully because of this problem.)

**Comment by jwokaty** [comment]
@hpages The long tests seem to create a meat file rather than a directory. I thought initially that I had configured it incorrectly, but now think it's an issue with the code. Should the `meat` directory be created and populated in the prerun since this is when the meat-index is created?

**Comment by hpages** [comment]
Yes, prerun should create and populate the `meat` directory. Did you run prerun? I don't see that in the log on nebbiolo1.

**Comment by hpages** [comment]
Also it seems that, in the case of the long tests builds, `BBS-run.py` (invoked by `run.sh`) should create/recreate the `meat` folder no matter what prerun did:
https://github.com/Bioconductor/BBS/blob/db72a839143c50ff4fc288c0fff5cd43d30cc17f/BBS-run.py#L615-L616

So you're saying that `bbs.fileutils.remake_dir()` fails to create/recreate the folder?

**Comment by jwokaty** [comment]
I just ran 'run' today manually and removed the meat file before I switched to testing in jetstream. If you look at the Saturday logs, you'll see prerun completed before the run, which is displaying the error. A meat file gets created I believe during run since a meat directory isn't created during prerun.

**Comment by hpages** [comment]
Looking at the code in `BBS/3.19/bioc-longtests/nebbiolo1/prerun.sh` and `BBS/BBS-prerun.py`, it seems that prerun does not create the `meat` folder in the case of the long tests builds, so I'm taking this back.

Seems like the question is why the call to `bbs.fileutils.remake_dir()` in `BBS-run.py` fails to create the folder. Sounds like a bug in `bbs.fileutils.remake_dir()`. Maybe we didn't run into this problem in the past because someone would manually create the `meat` folder on the builders? Doing so seems to actually work around the problem but we should still try to understand the issue with `bbs.fileutils.remake_dir()`.

**Comment by hpages** [comment]
The problem is actually in `get_list_of_target_pkgs()`: https://github.com/Bioconductor/BBS/blob/db72a839143c50ff4fc288c0fff5cd43d30cc17f/BBS-run.py#L175-L186

The call to `BBSutils.downloadFile()` wants to download the meat-index file (`meat-index.dcf`) to the `meat/` _folder_. In case this folder does not exist, `BBSutils.downloadFile()`  will instead download the file to the `meat` _file_. This follows the behavior of Unix commands `cp` or `mv`. However, in the case of the long-tests builds, `get_list_of_target_pkgs()` gets called _before_ the `meat/` folder actually exists. `get_list_of_target_pkgs()` should work and do the right thing whether `meat/` already exists or not. This can easily be achived by adding:
```
    if not os.path.isdir(BBSvars.meat_path):
        os.mkdir(BBSvars.meat_path)
```
right before the call to `BBSutils.downloadFile()`.

Another problem that is kind of orthogonal to that is the fact that `bbs.fileutils.remake_dir()` won't do anything if the directory to create/recreate is actually a file. We should change this to either:
1. remove the file then create the dir
2. or don't do anything and fail hard

I think I have a slight preference for 2. because seeing a file where a directory is actually expected is the sign that something went wrong already and trying to continue at all cost (like with 1.) is very unlikely to end well.

I'll prepare a PR.

**Comment by hpages** [comment]
@jwokaty The long test runs are still broken and will remain broken on palomino3 and merida1 until someone removes the erroneous `meat` files there. I just did it on merida1. Can you take care of palomino3? Thanks
