### ISSUE TITLE
Dev BBS for dummy instance

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#315]
@almahmoud @hpages @vjcitn I have a Jetstream instance running BBS code that is very much live. We need strategies to allow us to run a development version of the BBS and safe guard against build products like tar balls (during propagation) and the reports (during postrun) produced in these environments from going "live".

The BBS uses rsync to transfer files from the different operating systems. For example, in 3.17, we have rsync defined in https://github.com/Bioconductor/BBS/blob/b9ce223a52085418cdb95fd561d6d1db3a34afa0/3.17/config.sh#L12. The actual line performing rsync at https://github.com/Bioconductor/BBS/blob/b9ce223a52085418cdb95fd561d6d1db3a34afa0/3.17/bioc/nebbiolo1/postrun.sh#L44 and the location specified at https://github.com/Bioconductor/BBS/blob/b9ce223a52085418cdb95fd561d6d1db3a34afa0/3.17/bioc/nebbiolo1/config.sh#L53, which is to master.bioconductor.org

We could probably export a `DEVELOPMENT` environment variable in the config.sh or config.bat of the Bioc version directory and add conditionals to the `postrun.sh` to prevent running rsync.

The nodes/machines involved in the BBS need to rsync to get the snapshot of the repositories then run INSTALL, BUILD, etc, then send back the build artifacts to the primary builder, which rsyncs all artifacts to master during postrun for the reports then propagation for the tar balls, binaries, etc. It also needs to clone repositories.

@almahmoud had some additional suggestions, such as putting the reports in a bucket, or changing the way it's using keys. Could you clarify your suggestions here? I know they depend on how the BBS is set up.

This could be a separate issue, but we also need a way mock configurations so that we can tests on the BBS code.

**Comment by hpages** [comment]
Why not just edit `BBS_PUBLISHED_REPORT_DEST_DIR` and/or any other variable defined [here](https://github.com/Bioconductor/BBS/blob/b9ce223a52085418cdb95fd561d6d1db3a34afa0/3.18/bioc/nebbiolo2/config.sh#L35-L53) to point to the destinations of your choice for the reports and propagation of build products? This is what I do when I run BBS on my laptop for testing purpose.

Sorry if I'm missing something.

**Comment by almahmoud** [comment]
For context: after the accident of overwriting the live reports last week, Vince asked if I had any thoughts on ways to prevent that kind of accident from happening, so I spitballed some ideas to make it harder for experimenting to lead to user-facing changes.

Broadly, the first thing I brought up is the idea that the JS2 instance that pushed to the production BBS VM probably was ssh-ing as a user with full write permissions, and the idea of potentially creating a separate user/group that cannot write to production paths, so have read-only group permissions on those but not be able to write there, so if a configuration is copied over without changing a path it would at least be caught before overwriting. I guess that would potentially lead to one key for a production user and another for an experimental user, and I was wondering if something like that maybe already exists for how Martin was brought in for the ARM64 builds.

Separately, I brought up the idea of separating what is being served to users from the development portions more generally, with again the caveat that I am not sure how the current system is architected so this might not make sense. I suggested the idea of making the public reports one step further away rather than serving them directly from a particular VM but rather pushing them to buckets, and potentially having some checks in that final push to avoid inadvertent pushes to the user-facing reports (and if this is more generally done for tar balls as well, might also minimize cost if the tar balls are pulled from S3 rather than a VM)

**Comment by jwokaty** [comment]
@hpages Yes, that can be done, but you should change the configuration for every build.

@almahmoud I don't know the whole details but I think ssh keys were avoided for the experimental build and that the primary builder runs a cronjob to periodically rsync build products from the experimental machine.

I think the simplest solution is a programmatic one with documentation or just documentation because I would have saved a lot of time/frustration had I changed the configuration. We use the same user/key scheme for the machines, which is the problem, so I removed the key my Jetstream instance. I just need to change how it clones repos so it doesn't need a key. I don't need to rsync.

**Comment by hpages** [comment]
Thanks @almahmoud for providing some context.

@jwokaty Don't you have to register your testing machine in `BBS/nodes/` anyway as well as create a `BBS/3.18/bioc/<node_name>/` folder with a custom `config.sh` file in it etc...? It's not like you can clone BBS on the machine and immediately start the builds without doing a little bit of config work. The config work is a one time thing and you could commit it to Github for further use. I'm not sure why you would need to "change the configuration for every build" but again I might not have all the context here.

Let's be careful to not design a solution around a one time goof that could possibly introduce more complexity and more oportunities for more goofs in the future.

**Comment by hpages** [comment]
@jwokaty About the use of SSH keys:

_If your dummy instance is a standalone or central builder_ then BBS will only use rsync over SSH to push the report to its destination, that's all! (It would also use rsync over SSH to propagate packages to their destination but I'm assuming that you don't run the propagation stuff on the dummy instance.)

In other words, you should be able to run the builds without any SSH key on the dummy instance. In particular no SSH key is needed to clone the package repos from git.bioconductor.org.

So no `~biocbuild/.ssh/id_rsa` file means no risk to push things to user facing places.
