### ISSUE TITLE
update R on devel builders

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#367]

**Comment by hpages** [comment]
Are you sure about that @jwokaty? What about palomino3 and merida1?

**Comment by jwokaty** [comment]
The way I understood your message was that we should update nebbiolo2 and the any machine with the problematic versions, which was only nebbiolo1. I didn't understand from your messages that I should also update palomino3 and merida1, but I can do this and I can also ask Martin to update kunpeng2. Since CRAN is updating from tomorrow, I am not sure if I should update but maybe it doesn't matter and I should do it anyway since we expect that it will be bad.

**Comment by hpages** [comment]
There's been a lot of messages on Slack, both in the devteam-bioc Slack and the community-bioc Slack, so I'm not sure which one you're referring to.

Note that nebbiolo2 is a different story: it's a release builder and the need to update there only came up today (Tuesday, in the morning), in the context of the **zellkonverter** discussion on the community-bioc Slack (biocpython channel).

However I think you opened this issue before that, on Monday (yesterday), after my "We should probably consider updating R on the devel builders" comment on the devteam-bioc Slack (also from yesterday). Turns out that the **zellkonverter** issue made it more urgent to update nebbiolo1, so I did it this morning, but that doesn't mean that the other devel builders should no longer be updated.

Thanks.

**Comment by hpages** [comment]
W.r.t. kunpeng2, maybe we can wait before asking Martin to update.

Of all the devel builders kunpeng2 has the most recent R and it took several days for BBS to install all the package deps on the machine (even like that, a bunch of deps would consistently fail to install so Martin had to manually install them). So given that it's so hard for kunpeng2 to be back its feet again after an update of R, maybe we should wait until the next update on our builders before asking Martin to do the same. That will probably be somewhere in December.

Thanks again!

**Comment by martin-g** [comment]
Just let me know and I will update it!
It is not a problem for me to install the problematic (big) packages manually! I have a script that collects the missing packages from the logs and then I just run `BiocManager::install(c("package1", "p2", ...))`

**Comment by hpages** [comment]
Good to know. Thanks @martin-g!

**Comment by jwokaty** [comment]
I'm closing this since Palomino3 and merida1 were updated.
