### ISSUE TITLE
git_branch in source tarball for BiocVersion

### ISSUE THREAD

**Issue by almahmoud** [Bioconductor/BBS#369]
The source tarball https://www.bioconductor.org/packages/release/bioc/src/contrib/BiocVersion_3.18.0.tar.gz has in the DESCRIPTION file `git_branch: devel` which is tripping up some of the building scripts I use. This is not true for `AnnotationHub` source tarball for example. Manually `sed`-ing it for my purpose so not a blocker, but thought I should flag it

**Comment by hpages** [comment]
Thanks Alex.

This is actually expected:
```
git_url: https://git.bioconductor.org/packages/BiocVersion
git_branch: devel
git_last_commit: 1b82044
git_last_commit_date: 2023-04-25
Date/Publication: 2023-04-25
NeedsCompilation: no
Packaged: 2023-04-25 20:08:37 UTC; biocbuild
```
As the last commit date suggests, `BiocVersion_3.18.0.tar.gz` was built/packaged/published in April. This happened at the same time that we were doing the 3.17 release, and when 3.18 became the new devel. So _this_ tarball was indeed made from the `devel` branch and propagated to the 3.18 repos. There was no `RELEASE_3_18` branch at the time.

Concretely, the `git_` fields that BBS injects in the `DESCRIPTION` files can be used to track the exact git commit/branch that was used to build the package tarball. In this case, doing `git checkout devel && git reset --hard 1b82044` will give you that. In other words, `git_branch: devel` actually reflects the truth, strictly speaking, and serves its purpose, even if it's admitedly a little bit confusing in this case.

Note that we don't see this for other packages because they all got bumped last month before the 3.18 release, and right before the creation of the `RELEASE_3_18` branch. E.g. **Biobase** 2.62.0 (BioC 3.18) has:
```
git_url: https://git.bioconductor.org/packages/Biobase
git_branch: RELEASE_3_18
git_last_commit: 8201fbb
git_last_commit_date: 2023-10-24
Date/Publication: 2023-10-24
NeedsCompilation: yes
Packaged: 2023-10-24 20:24:56 UTC; biocbuild
```
That `8201fbb` commit is the version bump from 2.61.0 to 2.62.0.

However, we don't bump **BiocVersion** again in release the day before a release.

Ok so should we do something about it?

Some context: We use the [`bump_version_and_create_branch.py`](https://github.com/Bioconductor/BBS/blob/devel/utils/bump_version_and_create_branch.py) script to perform this "bump and branch" process on the day before a release. As you can see, **BiocVersion** is a hardcoded exception to the rule: for this package we skip the 1st version bump and do the 2nd version bump only.

So if we want to change that, the simplest solution would be to modify `bump_version_and_create_branch.py` to bump **BiocVersion** from X.Y.Z to X.Y.(Z+1) for the 1st bump. Second bump would not change i.e. it would still go from X.Y.Z to X.(Y+1).0 like for any other software package. This means that on the day before the 3.19 release (in Spring), we'll bump **BiocVersion** from 3.19.1 to 3.19.2 in `devel`, then create the `RELEASE_3_19` branch out of `devel`, then bump to 3.20.0 in `devel` again.

Would that work?

To retroactively "fix" this in BioC 3.18, we just need to manually bump **BiocVersion** from 3.18.0 to 3.18.1 in the `RELEASE_3_18` branch. Would that be ok with you @LiNk-NY?

**Comment by LiNk-NY** [comment]
Yes, I bumped the patch version of `BiocVersion` in `RELEASE_3_18`

**Comment by hpages** [comment]
Thanks Marcel!

**Comment by almahmoud** [comment]
Thanks both for the thorough explanation, really helps better understand the system overall, and for the change!
I'll close the issue since it's been resolved

**Comment by hpages** [comment]
CRAN injects the following fields in the package tarballs that they publish:
```
Repository: CRAN
Date/Publication: 2023-07-11 08:40:02 UTC
```
For Bioconductor packages we also inject `Date/Publication` but not `Repository`. I made a change to BBS this morning to also inject the later. It will look like this:
```
Repository: Bioconductor 3.19
Date/Publication: 2023-11-16
```
Maybe this is really what you are after @almahmoud? That is, what Bioconductor version the package tarball belongs to rather than what git branch it's coming from? Unlike the `git_branch` field, the `Repository` field will be a reliable way to get that info.

Note that this won't be retroactive (packages that are already published won't be touched). However, starting with the next daily propagation tomorrow, newly published packages will have the `Repository` field.

**Comment by almahmoud** [comment]
This is great! I'll bring it up for dh-r (https://salsa.debian.org/r-pkg-team/dh-r/)
