### ISSUE TITLE
Update Install Python in Mac Doc

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#382]
I don't think we need to `brew install python` anymore as described in https://github.com/Bioconductor/BBS/blob/devel/Doc/Prepare-macOS-Big-Sur-HOWTO.md#211-install-python-3 since tensorflow is now available for newer python versions, so this section in the documentation needs to be rewritten.  Maybe it just needs to be a newer version or install the required dependencies (maybe we should also note what packages require them?). We should also put `export PATH=/opt/R/x86_64/bin:$PATH` or `export PATH=/opt/R/arm64/bin:$PATH` in `/etc/profile`.

Note that brew installing some packages, such as mono and salt may require a version of python to be brew installed and also openssl. In these cases, we should `brew uninstall --ignore-dependencies $PACKAGE` for the package (maybe `brew autoremove` too?). If `brew install` symlinks a brewed python, remove the link with `brew unlink $PACKAGE`.

Note: without a brewed openssl, it seems that pip3 will fail to update because it needs ssl, which is why we should use the default installed python instead.

On merida1, need to `brew uninstall python@3.11` and `pip3 install` dependencies since it is currently showing an ssl error visible at the end of `pip3 list`.

**Comment by hpages** [comment]
Yes please get rid of the brewed Python3. It's been a while since we don't need it anymore. See https://github.com/Bioconductor/BBS/pull/182#issuecomment-1218903180 (from August 2022).

If it comes back as the dependency of something else that we need to brew, and if the installation is "keg-only", then it should not be a problem because "keg-only" means that it won't be in the `PATH`. So hopefully we won't need to use `brew uninstall --ignore-dependencies`, which is something we should not use lightly and only as a very last resort.

> We should also put `export PATH=/opt/R/x86_64/bin:$PATH` or `export PATH=/opt/R/arm64/bin:$PATH` in `/etc/profile`.

Is this related to Python? If not then maybe we can discuss this in a separate issue?

Thanks

**Comment by jwokaty** [comment]
More related to https://github.com/Bioconductor/BBS/issues/378, which is also related to this issue. I've put it there.
