### ISSUE TITLE
Information on info.dcf printed multiple times

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#397]
Information in package/raw-results/info.dcf is written multiple times. It should be written once. See https://bioconductor.org/checkResults/3.19/bioc-LATEST/icetea/raw-results/info.dcf as an example.

**Comment by hpages** [comment]
I think that the problem is that `write_info_dcf()` is called several times on the same package, once for each build node (e.g. 4 times in the example above). It should only be called once on each package.

So instead of being called in `make_node_LeafReports()` [here](https://github.com/Bioconductor/BBS/blob/9ebb2cf20e70e4bebf24a2a824a67193de821b08/BBS-report.py#L1760) (the `make_node_LeafReports()` function is called for each build node), a good place to call it would be in `make_all_LeafReports()` (this function is called only once) right after the creation of the `raw-results/` subfolder (line 1856):
```
        if not no_raw_results:
            os.mkdir(os.path.join(pkg, 'raw-results'))
            write_info_dcf(pkg)
```
Also the function does not need to have the `node_id` argument.
