### ISSUE TITLE
BBS should run 'svn-clean' on MEAT0 after updating, before proceeding

### ISSUE THREAD

**Issue by dtenenba** [Bioconductor/BBS#58]
If someone were to install a package (like IRanges) directly from MEAT0, this could create .o files in the source tarballs that we use to bootstrap the build system. Then when installing such a package it will skip compilation, which is not what we want.

We should have the build system run `svn-clean` after (or before?) doing `svn up` on the `MEAT0` directory. This will remove all files not checked into svn.

NB: This requires `svn-clean` by installed by doing:

```
sudo apt-get install subversion-tools
```

Thanks to @hpages for reporting this.

**Comment by hpages** [comment]
Now that we've switched from Subversion to Git, this cleaning would need to be done with `git clean` instead of `svn-clean`. But do we still want to do this? I'm inclined to say "no".

We should _never_ go on a build machine and run `R CMD INSTALL` on one of the Git repos in `MEAT0` in the first place. If we need to troubleshoot a package installation on a build machine, it's easy enough to clone the package in a temporary location instead of using the Git repo in `MEAT0`.
