### ISSUE TITLE
Reliable timeout for computing code coverage 

### ISSUE THREAD

**Issue by aoles** [Bioconductor/BBS#63]
The current approach using `withTimeout` in https://github.com/Bioconductor/BBS/blob/master/utils/compute_coverage.R doesn't seem to be reliable enough, e.g. the script hangs on BiocParallel.

**Comment by vobencha** [comment]
Hi @aoles ,
Is this still an active issue or can we close it?

**Comment by aoles** [comment]
Thanks @vobencha. It still is, in fact it has been the reason why I haven't been able to roll out the modified coverage-computing scripts to production yet. I tried running them a few times, but each time there was some offending package which caused the whole process to stall. As I didn't change the original concept of an R script iterating over packages to call `package_coverage`, I am now starting to wonder how this approach was working before. Maybe we were just lucky, or in the meantime there have bee some changes e.g. in covr which made the whole process more fragile.

For the moement I think that the only sane way to compute the coverage is to completely overhaul the whole script to use the well established and robust BBS mechanisms to kill rogue processes. I'm happy to discuss more.

**Comment by vobencha** [comment]
@aoles , thanks for letting me know. We talked about this briefly as a group today and think at this point we should let the coverage badges go. 

As you mentioned before, the current approach is already a 'short circuit' since we're trying to modify the current scripts to avoid using codecov.io. Adding coverage computations to the BBS infrastructure is not a direction we want to go ... and mirroring the repositories to a public git service is not an option right now. So, all in all I think we've explored the avenues available and can call it done.

Thanks for working on this. Sorry it didn't have a more rewarding ending!
Valerie
