### ISSUE TITLE
R_CHECK_ENVIRON=~/.R/bioc-check.Renviron instead of R_ENVIRON_USER=~/.Renviron.bioc

### ISSUE THREAD

**Issue by HenrikBengtsson** [Bioconductor/BBS#74]
Regarding https://github.com/Bioconductor/BBS/blob/master/3.11/Renviron.bioc, I think you want to use `R_CHECK_ENVIRON` instead of `R_ENVIRON_USER`.  From `?base::Startup`:

_`R CMD check` and `R CMD build` do not always read the standard startup files, but they do always read specific `Renviron` files. The location of these can be controlled by the environment variables `R_CHECK_ENVIRON` and `R_BUILD_ENVIRON`. If these are set their value is used as the path for the Renviron file; otherwise, files ‘`~/.R/check.Renviron`’ or ‘`~/.R/build.Renviron`’ or sub-architecture-specific versions are employed._

So, I suggest renaming your `Renviron.bioc` to something like `bioc-check.Renviron` and then tell people to use:
```r
R_CHECK_ENVIRON=~/.R/bioc-check.Renviron
```
when checking.  If `--as-cran` didn't exist, I'd imagine CRAN would ask us to use something like:
```r
R_CHECK_ENVIRON=~/.R/cran-check.Renviron
```

**Comment by HenrikBengtsson** [comment]
Of course, you could also ask people to create a `~/.R/check.Renviron` file and add the Bioconductor check env vars directly to that file.  That way the would not have to specify `R_CHECK_ENVIRON` at all; all `R CMD check ...`:s will pick that up automatically.

**Comment by hpages** [comment]
Hi Henrik,

This file is the place where I want to have any environment variable that controls the behavior of R in  any context i.e. during an interactive session, `R CMD build`, or `R CMD check`. For example it can define things like `_R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_` or `_R_CLASS_MATRIX_ARRAY_` (right now it doesn't but it was at some point and it could again in the future). I think it makes it easier for everybody to have all the R-controlling environment variables used by the build system in a single file than to have them split in several files.

This is why the file is named `Renviron.bioc` and not something like `bioc-check.Renviron`, and also why I suggest to use `R_ENVIRON_USER` and not `R_CHECK_ENVIRON`.

H.

**Comment by HenrikBengtsson** [comment]
> ... I want to have any environment variable that controls the behavior of R in any context i.e. during an interactive session, `R CMD build`, or `R CMD check`.

I see, and my bad, I found this file for the purpose of `R CMD check` and missed the other parts.

Q. I'm curious in what way there is a need for a custom setup for building Bioc packages?  Is that more just of just-in-case, or is there an actual need?

Ideally, R would support customized check settings, e.g. `--flavor=bioc`, `--flavor=cran` and so on, so one could do:
```
$ R CMD check --flavor=bioc ...
```
That could help to avoid lots of confusion.  But that's a different topic.


A side comment:  Thanks to your reply, I (again) dug into the details on what is happening under the hood when doing a `R CMD check ...` call.  I have incorrectly assumed that `R CMD check ...` is running everything in a `--vanilla` setup and definitely so when using `--as-cran`.  So, I was somewhat surprised that `R_ENVIRON_USER` settings would "survive" - but they do with:
```sh
$ R CMD check ...
```
but not with:
```sh
$ R --vanilla CMD check ...
```
I probably come back to this realization about once a decade. Oh well...

Details: When calling `R CMD command` the following happens:

1. `R` is called
2. `R` calls the internal `$R_HOME/bin/Rcmd` script (after setting some env vars)
3. `Rcmd` calls the internal `$R_HOME/bin/check` script (after setting some env vars)
4. The `check` script calls `tools:::.check_packages()` via `${R_HOME}/bin/R" --no-restore --no-echo ...`

On Windows, it's slightly different but it basically works the same.

I'm closing, but please see above question.

**Comment by hpages** [comment]
There is no need strictly speaking for a custom setup for building Bioc packages and we've actually been building/checking packages without setting any of these environment variables for the last 15 years (basically since the beginning of the build system). We only started using them a few months ago (around December 2019 IIRC) for the 3.11 daily builds. The Single Package Builder (SPB) that is used to build/check packages during the submission process has been doing this for longer.

Our approach to how we manage these settings is completely adhoc and depends very much on the need of the moment. The general idea is to catch more potential problems in package code but sometimes we also need to deal with temporary situations (e.g. `_R_CLASS_MATRIX_ARRAY_` setting).

Personally I'm not a big fan of using these settings -- and this is why I intendedly stayed away from them for so long -- because, as you say, they tend to create a lot of confusion. But the SPB uses them (not my choice), and not using them consistently for all our builds also tends to create confusion. Also, thanks to @nturaga, we recently started to provide a docker image with the same settings so it's become much easier for developers to reproduce our setup. So now we're using these settings consistently across the SPB, the daily builds, and on the devel docker image.

Yes something like `R CMD check --flavor=bioc` would be great but, as you said, that's another story.
